//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp53.Properties {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApp53.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _1 {
            get {
                object obj = ResourceManager.GetObject("1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _204 {
            get {
                object obj = ResourceManager.GetObject("204", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _204_2 {
            get {
                object obj = ResourceManager.GetObject("204_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap a {
            get {
                object obj = ResourceManager.GetObject("a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap a1 {
            get {
                object obj = ResourceManager.GetObject("a1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap b {
            get {
                object obj = ResourceManager.GetObject("b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap Blue_Orange_Modern_Abstract_Playful_Memory_Game_Presentation__1_ {
            get {
                object obj = ResourceManager.GetObject("Blue Orange Modern Abstract Playful Memory Game Presentation (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap Blue_Orange_Modern_Abstract_Playful_Memory_Game_Presentation__1_1 {
            get {
                object obj = ResourceManager.GetObject("Blue Orange Modern Abstract Playful Memory Game Presentation (1)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap Blue_Orange_Modern_Abstract_Playful_Memory_Game_Presentation__2_ {
            get {
                object obj = ResourceManager.GetObject("Blue Orange Modern Abstract Playful Memory Game Presentation (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap Blue_Orange_Modern_Abstract_Playful_Memory_Game_Presentation__2_1 {
            get {
                object obj = ResourceManager.GetObject("Blue Orange Modern Abstract Playful Memory Game Presentation (2)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap Blue_Orange_Modern_Abstract_Playful_Memory_Game_Presentation__2_2 {
            get {
                object obj = ResourceManager.GetObject("Blue Orange Modern Abstract Playful Memory Game Presentation (2)2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap Blue_Orange_Modern_Abstract_Playful_Memory_Game_Presentation__3_ {
            get {
                object obj = ResourceManager.GetObject("Blue Orange Modern Abstract Playful Memory Game Presentation (3)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap Blue_Orange_Modern_Abstract_Playful_Memory_Game_Presentation__3_1 {
            get {
                object obj = ResourceManager.GetObject("Blue Orange Modern Abstract Playful Memory Game Presentation (3)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap Blue_Orange_Modern_Abstract_Playful_Memory_Game_Presentation__3_2 {
            get {
                object obj = ResourceManager.GetObject("Blue Orange Modern Abstract Playful Memory Game Presentation (3)2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap Mavi_Cesur_Minimalist_Oyun_Arayüzü_Instagram_Gönderisi__1_ {
            get {
                object obj = ResourceManager.GetObject("Mavi Cesur Minimalist Oyun Arayüzü Instagram Gönderisi (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap Mavi_Cesur_Minimalist_Oyun_Arayüzü_Instagram_Gönderisi__1_1 {
            get {
                object obj = ResourceManager.GetObject("Mavi Cesur Minimalist Oyun Arayüzü Instagram Gönderisi (1)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap Mavi_Cesur_Minimalist_Oyun_Arayüzü_Instagram_Gönderisi__1_2 {
            get {
                object obj = ResourceManager.GetObject("Mavi Cesur Minimalist Oyun Arayüzü Instagram Gönderisi (1)2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap Mavi_Cesur_Minimalist_Oyun_Arayüzü_Instagram_Gönderisi__1_3 {
            get {
                object obj = ResourceManager.GetObject("Mavi Cesur Minimalist Oyun Arayüzü Instagram Gönderisi (1)3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap Mavi_Cesur_Minimalist_Oyun_Arayüzü_Instagram_Gönderisi__1_4 {
            get {
                object obj = ResourceManager.GetObject("Mavi Cesur Minimalist Oyun Arayüzü Instagram Gönderisi (1)4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap Mor_siyah_Uzay_Yıldızlar_Arkaplan_Masaüstü_Duvar_Kağıdı {
            get {
                object obj = ResourceManager.GetObject("Mor siyah Uzay Yıldızlar Arkaplan Masaüstü Duvar Kağıdı", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap Mor_siyah_Uzay_Yıldızlar_Arkaplan_Masaüstü_Duvar_Kağıdı__1_ {
            get {
                object obj = ResourceManager.GetObject("Mor siyah Uzay Yıldızlar Arkaplan Masaüstü Duvar Kağıdı (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap Puan_tablosu_rank_star_rank_game_oyuncu_sıralama__4_ {
            get {
                object obj = ResourceManager.GetObject("Puan tablosu rank star rank game oyuncu sıralama (4)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap Renkli_Çıkartmalar_ve_Rozetler_Hafıza_Oyunu_Eğlenceli_Sunum___Kopya___Kopya {
            get {
                object obj = ResourceManager.GetObject("Renkli Çıkartmalar ve Rozetler Hafıza Oyunu Eğlenceli Sunum - Kopya - Kopya", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap Sarı_Yeşil_Mavi_Dijitalizm_Temel_Sade_Sunum {
            get {
                object obj = ResourceManager.GetObject("Sarı Yeşil Mavi Dijitalizm Temel Sade Sunum", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap Sarı_Yeşil_Mavi_Dijitalizm_Temel_Sade_Sunum__1_ {
            get {
                object obj = ResourceManager.GetObject("Sarı Yeşil Mavi Dijitalizm Temel Sade Sunum (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap Sarı_Yeşil_Mavi_Dijitalizm_Temel_Sade_Sunum__1___1_ {
            get {
                object obj = ResourceManager.GetObject("Sarı Yeşil Mavi Dijitalizm Temel Sade Sunum (1) (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap Sarı_Yeşil_Mavi_Dijitalizm_Temel_Sade_Sunum__1_1 {
            get {
                object obj = ResourceManager.GetObject("Sarı Yeşil Mavi Dijitalizm Temel Sade Sunum (1)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap Sarı_Yeşil_Mavi_Dijitalizm_Temel_Sade_Sunum1 {
            get {
                object obj = ResourceManager.GetObject("Sarı Yeşil Mavi Dijitalizm Temel Sade Sunum1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap WhatsApp_Image_2022_12_20_at_21_29_05 {
            get {
                object obj = ResourceManager.GetObject("WhatsApp Image 2022-12-20 at 21.29.05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap WhatsApp_Image_2022_12_20_at_21_291 {
            get {
                object obj = ResourceManager.GetObject("WhatsApp Image 2022-12-20 at 21.291", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap WhatsApp_Image_2022_12_25_at_01_53_10 {
            get {
                object obj = ResourceManager.GetObject("WhatsApp Image 2022-12-25 at 01.53.10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap WhatsApp_Image_2022_12_25_at_02_03_10 {
            get {
                object obj = ResourceManager.GetObject("WhatsApp Image 2022-12-25 at 02.03.10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap WhatsApp_Image_2022_12_25_at_15_50_04 {
            get {
                object obj = ResourceManager.GetObject("WhatsApp Image 2022-12-25 at 15.50.04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
